{
  "uid": "fa38dc3878b16c74",
  "name": "test_div_unusual2[b]",
  "fullName": "test_calc.TestDiv#test_div_unusual2",
  "historyId": "6a9e290fa7e8ea025d2ef75fc834d953",
  "time": {
    "start": 1597675959453,
    "stop": 1597675959453,
    "duration": 0
  },
  "status": "skipped",
  "statusMessage": "TypeError: unsupported operand type(s) for /: 'str' and 'str'",
  "statusTrace": "self = <Hogwarts_pytest_zuoye.testcode.test_calc.TestDiv object at 0x000001FEF96EDCF8>, calc_init = <sourcecode.calc_code.Calculator object at 0x000001FEF96B1F60>, div_unusual_data2 = 'b'\n\n    @pytest.mark.xfail(raises=TypeError)\n    def test_div_unusual2(self, calc_init, div_unusual_data2):\n>       result = calc_init.div(div_unusual_data2[0], div_unusual_data2[0])\n\ntest_calc.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <sourcecode.calc_code.Calculator object at 0x000001FEF96B1F60>, a = 'b', b = 'b'\n\n    def div(self, a, b):\n>       return a / b\nE       TypeError: unsupported operand type(s) for /: 'str' and 'str'\n\n..\\sourcecode\\calc_code.py:14: TypeError",
  "flaky": false,
  "newFailed": false,
  "beforeStages": [
    {
      "name": "div_unusual_data2",
      "time": {
        "start": 1597675959453,
        "stop": 1597675959453,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    },
    {
      "name": "calc_init",
      "time": {
        "start": 1597675959429,
        "stop": 1597675959429,
        "duration": 0
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    }
  ],
  "afterStages": [
    {
      "name": "calc_init::0",
      "time": {
        "start": 1597675959463,
        "stop": 1597675959464,
        "duration": 1
      },
      "status": "passed",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "shouldDisplayMessage": false,
      "attachmentsCount": 0,
      "hasContent": false,
      "stepsCount": 0
    }
  ],
  "labels": [
    {
      "name": "tag",
      "value": "run(order=4)"
    },
    {
      "name": "tag",
      "value": "@pytest.mark.xfail(raises=<class 'TypeError'>)"
    },
    {
      "name": "tag",
      "value": "div"
    },
    {
      "name": "suite",
      "value": "test_calc"
    },
    {
      "name": "subSuite",
      "value": "TestDiv"
    },
    {
      "name": "host",
      "value": "TJ-YF-262JLJ"
    },
    {
      "name": "thread",
      "value": "4968-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_calc"
    },
    {
      "name": "resultFormat",
      "value": "allure2"
    }
  ],
  "parameters": [
    {
      "name": "div_unusual_data2",
      "value": "'b'"
    }
  ],
  "links": [],
  "hidden": false,
  "retry": false,
  "extra": {
    "severity": "normal",
    "retries": [],
    "categories": [],
    "tags": [
      "div",
      "run(order=4)",
      "@pytest.mark.xfail(raises=<class 'TypeError'>)"
    ]
  },
  "source": "fa38dc3878b16c74.json",
  "parameterValues": [
    "'b'"
  ]
}